### ISSUE TITLE
Can't get it to work with namespaces

### ISSUE THREAD

**Issue by jume-dev** [jwbay/i18next-json-sync#1]
Hi
My files are organized in namespaces like this
- en
  - about.json
  - help.json
- fr
  - about.json
  - help.json

How can i use this setup with your tool? I can't get it to work

**Comment by jwbay** [comment]
That folder structure is not supported at the moment, just the inverse (about and help folders, with en.json and fr.json inside them) and I'm afraid I'm not likely to add it myself. I would accept a pull request that adds support, though.

**Comment by jume-dev** [comment]
Alright, i see what i can do

**Comment by jume-dev** [comment]
Can you give some hints where to start and what to change?

**Comment by httpete** [comment]
yes any hints, the code looks well structured but needs to be tweaked to handle the namespace way

**Comment by jwbay** [comment]
Hi, sorry for the long delay. I took a look and the assumption around the current structure is pretty deeply baked in. Here are the spots that would need to be adjusted at a minimum.

Turning the glob into groups of files:
https://github.com/jwbay/i18next-json-sync/blob/1a06e624e01fe49c6ee2e3bd9e5fcd79bfa9c499/src/index.ts#L80-L88 ()

The core loop over the file groups:
https://github.com/jwbay/i18next-json-sync/blob/1a06e624e01fe49c6ee2e3bd9e5fcd79bfa9c499/src/index.ts#L45-L65

The in-memory representation of a group of json files, and mapping between it and the disk:
https://github.com/jwbay/i18next-json-sync/blob/1a06e624e01fe49c6ee2e3bd9e5fcd79bfa9c499/src/LocalizationFolder.ts#L20-L77

It may be the most straightforward to add a new option that would switch inverted folder structures to the kind currently supported as they come in from the glob results, and switch them back when writing to disk. This would keep the processing step mostly unchanged.

If that approach changes more than the input/output spots, though, I'd prefer adding if statements as necessary. An option is probably unavoidable so we know how to resolve the glob results into json file groups.

**Comment by felixmosh** [comment]
Since this lib doesn't maintained anymore, 
I’ve published a total rewritten lib which:

1. Supports namespaces.
2. Full plural support, based on the real i18next pluralResolver.
3. Sorting secondary locale keys by primary language order.
4. Supports multiple locale folder structure, `{lng}/{namespace}`, `{namespace}/{lng}`.
5. Creates missing locale files.

And more!
https://github.com/felixmosh/i18next-locales-sync

**Comment by jwbay** [comment]
Please switch to the above library if you need this inverted directory support 👍
