### ISSUE TITLE
Would there be any interest in this project supporting YAML in addition to JSON

### ISSUE THREAD

**Issue by derek-pavao** [jwbay/i18next-json-sync#12]
We're going to be working with YAML files instead of JSON in our project that is using i18next. I like this project but it doesn't support YAML. 

If there is some interest in adding that support I'd be more than happy to put together a PR to add it. 

Thoughts?

**Comment by PredokMiF** [comment]
I was think about YAML too, but name of this project talking me that it should be another repo
