### ISSUE TITLE
Option to preserve key ordering of primary json

### ISSUE THREAD

**Issue by tpaik18** [jwbay/i18next-json-sync#13]
Hi, this package looks very useful, but unfortunately it is reordering all my JSON keys into alphabetical order. So my en.json got changed to, for example, 
```
    "april": "April",
    "august": "August",
    "december": "December",
    "february": "February",
    "january": "January",
    "july": "July",
    "june": "June",
    "march": "March",
    "may": "May",
    "november": "November",
    "october": "October",
    "september": "September"
```

I would much prefer to preserve the ordering in en.json which is logical and therefore helps the translator to translate. Can we have an option for this? Based on the example in your documentation, I did not expect the keys to reorder.

**Comment by felixmosh** [comment]
[i18next-locales-sync](https://github.com/felixmosh/i18next-locales-sync) supports this by default, check it out

**Comment by jwbay** [comment]
Please switch to the above package if you need this option 👍
