### ISSUE TITLE
--newKeysEmpty 'true' doesnt work on package json script

### ISSUE THREAD

**Issue by BLouzada** [jwbay/i18next-json-sync#14]
"i18n": "sync-i18n --files 'src/app/i18n/*.json' --primary pt_br --languages es --space 4 --newKeysEmpty 'true'"

this is my configuration, but the new keys added to es.json still using primary language text, i want it to be empty;

**Comment by jwbay** [comment]
Can you try `"i18n": "sync-i18n --files 'src/app/i18n/*.json' --primary pt_br --languages es --space 4 --newkeysempty"` ? I think yargs (the command line parser) is case-sensitive.

**Comment by jwbay** [comment]
Assuming this was fixed per above
