### ISSUE TITLE
Allow me to specify language code in the path

### ISSUE THREAD

**Issue by hgezim** [jwbay/i18next-json-sync#16]
It seems this pattern doesn't work:

```
$ ls static/locales/**/*.json
static/locales/cs/common.json  static/locales/de/common.json  static/locales/en/common.json
```

**Comment by rononiwu** [comment]
@hgezim Yea, I had the same issue. It seems no one is supporting this project anymore.

**Comment by felixmosh** [comment]
This https://github.com/felixmosh/i18next-locales-sync is supports namespaces out of the box

**Comment by jwbay** [comment]
Please switch to the above package if you need to support this inverted directory structure 👍
