### ISSUE TITLE
primary: 'zh' will don't work

### ISSUE THREAD

**Issue by WoeOm** [jwbay/i18next-json-sync#2]
sync({
  /** Audit files in memory instead of changing them on the filesystem and
    * throw an error if any changes would be made */
  check: false,
  /** Glob pattern for the resource JSON files */
  files: './js/i18n/languages/*.json',
  /** Primary localization language. Other language files will be changed to match */
  primary: 'zh',
  /** Language files to create if they don't exist, e.g. ['es, 'pt-BR', 'fr'] */
  createResources: ['fr'],
  /** Space value used for JSON.stringify when writing JSON files to disk */
  space: 4,
  /** Line endings used when writing JSON files to disk. Either LF or CRLF */
  lineEndings: 'LF'
})

sync en.json will be {}   , is empty;

 primary: 'zh' is fine

**Comment by jwbay** [comment]
Thank you for the bug report, and sorry for the long delay. This should be fixed with v2.2.0.
