### ISSUE TITLE
Plurals are not handled properly, it is not aligned with i18next

### ISSUE THREAD

**Issue by felixmosh** [jwbay/i18next-json-sync#22]
For example, 
```json
// en.json
{
   "one": "singular message",
   "one_plural": "plural message"
}
```

Should be for **he** (Hebrew) synced as 
```json
// he.json
{
   "one": "singular message",
   "one_0": "singular message",
   "one_1": "singular message",
   "one_2": "plural message",
   "one_3": "plural message",
}
```

Currently the sync will produce
```json
// he.json
{
   "one": "singular message",
   "one_plural": "plural message"
}
```
For more details there is a [playground](https://jsfiddle.net/sm9wgLze) that demonstrates it
It probably related to https://github.com/i18next/i18next/blob/master/src/PluralResolver.js

**Comment by felixmosh** [comment]
Solved in a new lib https://github.com/felixmosh/i18next-locales-sync

**Comment by jwbay** [comment]
Plural resolution is indeed likely out of date with i18next, especially w/ their v4 format. I'll open a new issue for v4. Glad you were able to get things working in your new lib 👍
