### ISSUE TITLE
Spaces are replaced with the literal text "4"

### ISSUE THREAD

**Issue by chsedotsh** [jwbay/i18next-json-sync#24]
If I run `npx sync-i18n --files ./locale/*.json --primary en --space 4`, my JSON ends up looking like this:
```json
{
4"_name": "English"
}
```

rather than

```json
{
    "_name": "English"
}
```

This does not happen on `2.3.1`, but happens on any newer version.

**Comment by fervailanti** [comment]
Same here... @chxseh Did you find any solution?

**Comment by jwbay** [comment]
Thanks for reporting! Fixed in v3.1.1
