### ISSUE TITLE
Problem with wildcards in the CLI example on OSX

### ISSUE THREAD

**Issue by dabide** [jwbay/i18next-json-sync#3]
When using wildcards in `package.json`as shown in the CLI example, globbing behaves unpredictably on OSX. In my case, I used `--files wwwroot/locales/*.json`. When run from the CLI, this caused globbing to be handled by the shell instead of Node, strangely enough resulting in the script only finding the first file in the folder.

Escaping the wildcards ensures that globbing is handled by Node, avoiding the unpredictability. Thus, the example should look like this:

```
"i18n": "sync-i18n --files \\*\\*/locales/\\*.json --primary en --languages es fr ja zh ko --space 2"
```

**Comment by jwbay** [comment]
From what I found, quoting works in addition to escaping and looks a little cleaner. Let me know if that's not the case.
