### ISSUE TITLE
End of lines and --check

### ISSUE THREAD

**Issue by martpie** [jwbay/i18next-json-sync#4]
can you add an option to have an end of line at the end of the localization files? I edit the keys manually and my editor automatically remove whitespaces and add an empty line at the end of the file, and the `--check` option fails because of that.

**Comment by jwbay** [comment]
There's actually an option for this as of v2.1.0 -- `finalNewline`. I just never documented it, and currently it's only supported on the node API and not the CLI. I'll try to address those soon 👍

**Comment by martpie** [comment]
Thank you! :)
