### ISSUE TITLE
i18next-json-sync file sync question

### ISSUE THREAD

**Issue by agarwal-m** [jwbay/i18next-json-sync#5]
I am new to this package and am trying to use it to sync different language files for my angular2/nodejs project. But the given usage is not working for me.

My lang file structure is (multiple levels deep):

- package.json
- public
  - app
    - assets
      - language
          - en.json
          - es.json
          - fr.json
          - ja.json

And my package.json has:

```
{ 
  "scripts": {
   ...
   "i18n": "sync-i18n --files './public/app/assets/language/*.json' --primary en --languages es fr ja",
   "check-i18n": "npm run i18n -- --check",
   ...
}
 "devDependencies": {
    ...
    "i18next-json-sync": "2.2.0",
    ...
  }
}
```

But when I run `npm run check-i18n` or `npm run i18n` I do not see any key/values being copied from en file (primary) to other language files. What am I missing?

**Comment by jwbay** [comment]
Your usage looks correct. Is there any chance you could share json content that isn't syncing, ideally just parts of two files, a primary and a target? The exact string values aren't super important (beyond whether they match the primary or not). It's probably a structural thing.

**Comment by agarwal-m** [comment]
I also thought it might depend upon json structure. My original file has a nested structure like:
```
//en.json
{
	"app": {
		"page": {
			"dashboard": "Dashboard",
			"devices": "Devices",
			"machines": "Machines"
		},
		"title": "Some kind of Title",
		"topBar": {
			"welcome": "Welcome, {{userName}} ({{userRole}})"
		}
	},
	"breadcrumb": {
		"allMachines": "All Machines",
		"machines": "Machines"
	},
	"common": {
		"add": "Add",
		"admin": "Admin",
		"cancel": "Cancel",
		"close": "Close",
		"delete": "Delete",
		"device": "Device"
       }
}
```
But later on I tried it with a really rudimentary structure as well, this:
```
{
	"key_one": "value",
	"book": "book",
	"book_plural": "books",
	"book1": "Turtle All the Way Down",
	"book2": "Tell the Wolves I'm Home"
}
```
Does the package has any minimum node / npm requirements? Or any known compatibility issues? I am using it with angular5:
npm 4.2.0
nvm 1.1.5
node 7.10.0

**Comment by jwbay** [comment]
Environmental stuff looks fine.

I tried dropping those structures into my tests and they both synced against targets as expected -- with a key to remove, and with no keys present, and with a deeply nested key missing. Assuming those are source/primary structures, could you share a target?

Another thing to try may be the node api instead of the CLI.

**Comment by agarwal-m** [comment]
Targets are exactly the same, except occasional missing keys. Let me try the node api way.

**Comment by nikolay-borzov** [comment]
Seems like I found the cause of this issue.
You don't need to wrap pattern in '' inside the script
```
 "i18n": "sync-i18n --files ./public/app/assets/language/*.json --primary en --languages es fr ja",
```
I use Win 10

**Comment by jwbay** [comment]
Closing out old issues. The above fix may be valid on Windows, but not a Unixy OS where the glob would be expanded by the shell. The CLI parser & code was updated recently, so if this is still an issue for anyone please open a new one
