### ISSUE TITLE
Should language files get translated?

### ISSUE THREAD

**Issue by ghost** [jwbay/i18next-json-sync#8]
Hi,

I created the node.js file with the default parameters. I'm using typescript so I have this script in package.json:
`"i18n": "ts-node ./scripts/node.js"`

This runs fine and generates the language files, but the language files are still in english. How can I get it to automatically translate the new keys to the proper language?

**Comment by jwbay** [comment]
This package does not translate localization strings. It only keeps key shapes/file structures in sync.
